apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: oct9
          artifact-id: 4c1f1eef-47cf-417b-ae13-933a12324efa
          target-environment: ASPM QA